"""
Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.

"""


def sum_of_even_fibonacci_members_until(n):
    even_fibonnaci = [2, 8]

    while even_fibonnaci[-1] < n:
        even_fibonnaci.append(even_fibonnaci[-1] * 4 + even_fibonnaci[-2])

    return sum(even_fibonnaci) - even_fibonnaci[-1]


print(sum_of_even_fibonacci_members_until(4000000))
